AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-swagger-api-sandbox

  SAM Template for swagger generated API Sandbox

Globals:
  Function:
    Timeout: 3

Parameters:
  SwaggerBucket:
    Type: String
    Description: The uploaded swagger.yaml
  StageName:
    Type: String
    Description: The API stage name
  AppName:
    Type: String
    Description: The API stage name

Resources:
  MelodyContentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AppName}-${StageName}-movie-contents
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - PUT
              - POST
              - DELETE
            AllowedOrigins:
              - '*'
            ExposedHeaders:
              - x-amz-server-side-encryption
              - x-amz-request-id
              - x-amz-id-2
            Id: MelodyContentsBucketCORS
            MaxAge: 3600
  FFMPEGLambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: ffmpeg 
      Description: FFMPEG for AWS Lambda
      ContentUri: build/layer
      CompatibleRuntimes:
        - python3.8
      LicenseInfo: GPL-2.0-or-later
      RetentionPolicy: Retain

  SwaggerAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
      Cors: "'*'"
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: !Ref 'SwaggerBucket'

  ConvertMovieFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/convert_movie
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 60
      Layers:
        - !Ref FFMPEGLambdaLayer
      Policies: 
        - S3CrudPolicy:
            BucketName: !Sub ${AppName}-${StageName}-movie-contents
      Events:
        S3Trigger:
          Type: S3
          Properties:
            Bucket: !Ref MelodyContentsBucket
            Events: s3:ObjectCreated:*
        # ProxyApiRoot:
        #   Type: Api
        #   Properties:
        #     RestApiId: !Ref SwaggerAPI
        #     Path: /src/comvert_movie
        #     Method: GET
  ConvertMovieFunctionPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ConvertMovieFunction
      Principal: apigateway.amazonaws.com

  GetMusicFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/get_music
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies: 
        - S3CrudPolicy:
            BucketName: !Sub ${AppName}-${StageName}-movie-contents      
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref SwaggerAPI
            Path: /src/get_music
            Method: GET
  GetMusicFunctionPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GetMusicFunction
      Principal: apigateway.amazonaws.com

  
