swagger: "2.0"
info:
  description: "swagger"
  version: "1.0.0"
  title: "Melody API App"
basePath: /${StageName}
schemes:
  - "https"
paths:

  /music/:
    get:
      tags:
        - "music"
      summary: "音声ファイルを取得する"
      operationId: "getMusic"
      responses:
        "200":
          description: "音声ファイルが取得できた"
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetMusicFunction.Arn}/invocations
        passthroughBehavior: when_no_templates
        httpMethod: POST
        type: aws_proxy
 
